// Proto definition for API service.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.20.1-devel
// 	protoc        v3.6.1
// source: rarc.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ResultsFromDB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ASN      string `protobuf:"bytes,1,opt,name=ASN,proto3" json:"ASN,omitempty"`
	Prefix   string `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Maxlen   int32  `protobuf:"varint,3,opt,name=maxlen,proto3" json:"maxlen,omitempty"`
	Ta       string `protobuf:"bytes,4,opt,name=ta,proto3" json:"ta,omitempty"`
	Mask     int32  `protobuf:"varint,5,opt,name=mask,proto3" json:"mask,omitempty"`
	Unixtime int64  `protobuf:"varint,6,opt,name=unixtime,proto3" json:"unixtime,omitempty"`
}

func (x *ResultsFromDB) Reset() {
	*x = ResultsFromDB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rarc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResultsFromDB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultsFromDB) ProtoMessage() {}

func (x *ResultsFromDB) ProtoReflect() protoreflect.Message {
	mi := &file_rarc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultsFromDB.ProtoReflect.Descriptor instead.
func (*ResultsFromDB) Descriptor() ([]byte, []int) {
	return file_rarc_proto_rawDescGZIP(), []int{0}
}

func (x *ResultsFromDB) GetASN() string {
	if x != nil {
		return x.ASN
	}
	return ""
}

func (x *ResultsFromDB) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *ResultsFromDB) GetMaxlen() int32 {
	if x != nil {
		return x.Maxlen
	}
	return 0
}

func (x *ResultsFromDB) GetTa() string {
	if x != nil {
		return x.Ta
	}
	return ""
}

func (x *ResultsFromDB) GetMask() int32 {
	if x != nil {
		return x.Mask
	}
	return 0
}

func (x *ResultsFromDB) GetUnixtime() int64 {
	if x != nil {
		return x.Unixtime
	}
	return 0
}

type ResultArr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*ResultsFromDB `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *ResultArr) Reset() {
	*x = ResultArr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rarc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResultArr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultArr) ProtoMessage() {}

func (x *ResultArr) ProtoReflect() protoreflect.Message {
	mi := &file_rarc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultArr.ProtoReflect.Descriptor instead.
func (*ResultArr) Descriptor() ([]byte, []int) {
	return file_rarc_proto_rawDescGZIP(), []int{1}
}

func (x *ResultArr) GetResults() []*ResultsFromDB {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_rarc_proto protoreflect.FileDescriptor

var file_rarc_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x72, 0x61, 0x72, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x72, 0x61,
	0x72, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x91, 0x01, 0x0a, 0x0d, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x73, 0x46, 0x72, 0x6f, 0x6d, 0x44, 0x42, 0x12, 0x10, 0x0a, 0x03, 0x41, 0x53, 0x4e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x41, 0x53, 0x4e, 0x12, 0x16, 0x0a, 0x06, 0x70,
	0x72, 0x65, 0x66, 0x69, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x72, 0x65,
	0x66, 0x69, 0x78, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x61, 0x78, 0x6c, 0x65, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x6d, 0x61, 0x78, 0x6c, 0x65, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x74,
	0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x6d,
	0x61, 0x73, 0x6b, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x6d, 0x61, 0x73, 0x6b, 0x12,
	0x1a, 0x0a, 0x08, 0x75, 0x6e, 0x69, 0x78, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x75, 0x6e, 0x69, 0x78, 0x74, 0x69, 0x6d, 0x65, 0x22, 0x3f, 0x0a, 0x09, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x41, 0x72, 0x72, 0x12, 0x32, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x72, 0x61, 0x72, 0x63,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x46, 0x72, 0x6f,
	0x6d, 0x44, 0x42, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x42, 0x09, 0x5a, 0x07,
	0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rarc_proto_rawDescOnce sync.Once
	file_rarc_proto_rawDescData = file_rarc_proto_rawDesc
)

func file_rarc_proto_rawDescGZIP() []byte {
	file_rarc_proto_rawDescOnce.Do(func() {
		file_rarc_proto_rawDescData = protoimpl.X.CompressGZIP(file_rarc_proto_rawDescData)
	})
	return file_rarc_proto_rawDescData
}

var file_rarc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rarc_proto_goTypes = []interface{}{
	(*ResultsFromDB)(nil), // 0: rarcproto.ResultsFromDB
	(*ResultArr)(nil),     // 1: rarcproto.ResultArr
}
var file_rarc_proto_depIdxs = []int32{
	0, // 0: rarcproto.ResultArr.results:type_name -> rarcproto.ResultsFromDB
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rarc_proto_init() }
func file_rarc_proto_init() {
	if File_rarc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rarc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResultsFromDB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rarc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResultArr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rarc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rarc_proto_goTypes,
		DependencyIndexes: file_rarc_proto_depIdxs,
		MessageInfos:      file_rarc_proto_msgTypes,
	}.Build()
	File_rarc_proto = out.File
	file_rarc_proto_rawDesc = nil
	file_rarc_proto_goTypes = nil
	file_rarc_proto_depIdxs = nil
}
